/*
https://ap16.salesforce.com/services/Soap/class/SensorService

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sen="http://soap.sforce.com/schemas/class/SensorService">
   <soapenv:Header>
      <sen:AllowFieldTruncationHeader>

      </sen:AllowFieldTruncationHeader>
      <sen:DebuggingHeader>

      </sen:DebuggingHeader>
      <sen:CallOptions>

      </sen:CallOptions>
      <sen:SessionHeader>
         <sen:sessionId>00D2w00000DMkx8!ARUAQL5X_NViRsSiBkDo3bVjKyTsPj4It3IkuO34AcBJtrAKx6RMQi8makzrx9fwXaFGki8tm757t_qnlIqVpSyMkKaLbtrp</sen:sessionId>
      </sen:SessionHeader>
   </soapenv:Header>
   <soapenv:Body>
      <sen:addSensorService>
         <sen:accountId>0012w00000MohGhAAJ</sen:accountId>
         <sen:sensorid>a002w00000CxCyDAAV</sen:sensorid>
         <sen:line>22</sen:line>
         <sen:line>17</sen:line>
         <sen:line>197</sen:line>
         <sen:line>23</sen:line>
         <sen:line>45</sen:line>
         <sen:line>14</sen:line>
         <sen:line>22</sen:line>
         <sen:line>43</sen:line>
         <sen:line>196</sen:line>
         <sen:line>24</sen:line>
         <sen:line>42</sen:line>
         <sen:line>198</sen:line>
         
      </sen:addSensorService>
   </soapenv:Body>
</soapenv:Envelope>
*/

public with sharing class SOAPClient {
    public SOAPClient() {

    }
}
